#!/bin/bash
echo "enter three numbers and i will find the greatest amontg the three "
read a
read b
read c
if [ $a -gt $b -a $a -gt $c ]
 then 
  echo "$a is the largest among the numbers"
 elif [ $b -gt $c -a $b -gt $a ]
  then 
   echo "$b is greatest"
else
 echo "$c is greatest"
fi

